const actionType = {
  GET_FRIENDS: 'GET_FRIENDS',
  GET_FRIENDS_PENDING: 'GET_FRIENDS_PENDING',
  GET_FRIENDS_REJECTED: 'GET_FRIENDS_REJECTED',
  GET_FRIENDS_FULFILLED: 'GET_FRIENDS_FULFILLED',

  ADD_FRIEND: 'ADD_FRIEND',
  ADD_FRIEND_PENDING: 'ADD_FRIEND_PENDING',
  ADD_FRIEND_REJECTED: 'ADD_FRIEND_REJECTED',
  ADD_FRIEND_FULFILLED: 'ADD_FRIEND_FULFILLED',

  PATCH_FRIEND: 'PATCH_FRIEND',
  PATCH_FRIEND_PENDING: 'PATCH_FRIEND_PENDING',
  PATCH_FRIEND_REJECTED: 'PATCH_FRIEND_REJECTED',
  PATCH_FRIEND_FULFILLED: 'PATCH_FRIEND_FULFILLED',

  DELETE_FRIEND: 'DELETE_FRIEND',
  DELETE_FRIEND_PENDING: 'DELETE_FRIEND_PENDING',
  DELETE_FRIEND_REJECTED: 'DELETE_FRIEND_REJECTED',
  DELETE_FRIEND_FULFILLED: 'DELETE_FRIEND_FULFILLED',

  GET_FRIENDS_LIST: 'GET_FRIENDS_LIST',
  GET_FRIENDS_LIST_PENDING: 'GET_FRIENDS_LIST_PENDING',
  GET_FRIENDS_LIST_REJECTED: 'GET_FRIENDS_LIST_REJECTED',
  GET_FRIENDS_LIST_FULFILLED: 'GET_FRIENDS_LIST_FULFILLED',
};

export default actionType;
