const actionType = {
  GET_USERS: 'GET_USERS',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
  GET_USERS_REJECTED: 'GET_USERS_REJECTED',
  GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
  
  ADD_USER: 'ADD_USER',
  ADD_USER_PENDING: 'ADD_USER_PENDING',
  ADD_USER_REJECTED: 'ADD_USER_REJECTED',
  ADD_USER_FULFILLED: 'ADD_USER_FULFILLED',
  
  PATCH_USER: 'PATCH_USER',
  PATCH_USER_PENDING: 'PATCH_USER_PENDING',
  PATCH_USER_REJECTED: 'PATCH_USER_REJECTED',
  PATCH_USER_FULFILLED: 'PATCH_USER_FULFILLED',
  
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_PENDING: 'DELETE_USER_PENDING',
  DELETE_USER_REJECTED: 'DELETE_USER_REJECTED',
  DELETE_USER_FULFILLED: 'DELETE_USER_FULFILLED',

  GET_USERS_LIST: 'GET_USERS_LIST',
  GET_USERS_LIST_PENDING: 'GET_USERS_LIST_PENDING',
  GET_USERS_LIST_REJECTED: 'GET_USERS_LIST_REJECTED',
  GET_USERS_LIST_FULFILLED: 'GET_USERS_LIST_FULFILLED',
};

export default actionType;
