const actionType = {
  SET_LOCATION: 'SET_LOCATION',

  GET_ADRESS: 'GET_ADRESS',
  GET_ADRESS_PENDING: 'GET_ADRESS_PENDING',
  GET_ADRESS_REJECTED: 'GET_ADRESS_REJECTED',
  GET_ADRESS_FULFILLED: 'GET_ADRESS_FULFILLED',
};

export default actionType;
