const actionType = {
  SET_AUTH: 'SET_AUTH',
  SET_AUTH_PENDING: 'SET_AUTH_PENDING',
  SET_AUTH_REJECTED: 'SET_AUTH_REJECTED',
  SET_AUTH_FULFILLED: 'SET_AUTH_FULFILLED',

  LOGIN: 'LOGIN',
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_REJECTED: 'LOGIN_REJECTED',
  LOGIN_FULFILLED: 'LOGIN_FULFILLED',

  REGISTER: 'REGISTER',
  REGISTER_PENDING: 'REGISTER_PENDING',
  REGISTER_REJECTED: 'REGISTER_REJECTED',
  REGISTER_FULFILLED: 'REGISTER_FULFILLED',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_PENDING: 'REFRESH_TOKEN_PENDING',
  REFRESH_TOKEN_REJECTED: 'REFRESH_TOKEN_REJECTED',
  REFRESH_TOKEN_FULFILLED: 'REFRESH_TOKEN_FULFILLED',

  LOGOUT: 'LOGOUT',
};

export default actionType;
