const actionType = {
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_NEW_NOTIFICATION: 'GET_NEW_NOTIFICATION',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  READ_NOTIFICATION: 'READ_NOTIFICATION',
  DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
};

export default actionType;
